apiVersion: v1
kind: Service
metadata:
  name: gateway-demo
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - port: 8280
      targetPort: 8280
      name: api
    - port: 8281
      targetPort: 8281
      name: management